tabItem("Data",
         sidebarLayout(
             sidebarPanel(
                 uiOutput("selectbox")
             ),
             mainPanel(
                 dataTableOutput('tbl')                 
             )
         )
)
